"""Regulator, prosecutor and law-enforcement press feeds (kind=enforcement)."""
from __future__ import annotations

from typing import List

from venombot.feeds import FeedSource

FEEDS: List[FeedSource] = [
    FeedSource(
        key='AU_FEDERAL_COURT_JUDGMENTS_RSS',
        name='Federal Court of Australia judgments',
        url='https://www.judgments.fedcourt.gov.au/rss/fca-judgments',
        language='en',
        region='AU',
        kind='enforcement',
        groups=['regulators', 'au'],
        license='public',
        max_age_days=2,
        notes='Court judgments (ASIC/AUSTRAC civil penalty cases); 1.6 MB feed.',
    ),
    FeedSource(
        key='EU_EUROJUST_PRESS_RSS',
        name='Eurojust press releases',
        url='https://www.eurojust.europa.eu/rss/press-releases.xml',
        language='en',
        region='EU',
        kind='enforcement',
        groups=['regulators', 'eu'],
        license='terms',
        max_age_days=2,
        notes='',
    ),
    FeedSource(
        key='EU_EUROPOL_NEWS_RSS',
        name='Europol news',
        url='https://www.europol.europa.eu/cms/api/rss/news',
        language='en',
        region='EU',
        kind='enforcement',
        groups=['regulators', 'eu'],
        license='terms',
        max_age_days=2,
        notes='No pubDate; dedupe by link.',
    ),
    FeedSource(
        key='EU_OLAF_NEWS_RSS',
        name='OLAF news',
        url='https://anti-fraud.ec.europa.eu/node/2/rss_en',
        language='en',
        region='EU',
        kind='enforcement',
        groups=['regulators', 'eu'],
        license='CC-BY',
        max_age_days=2,
        notes='Rarely names individuals.',
    ),
    FeedSource(
        key='UK_FCA_WARNINGS_RSS',
        name='FCA warnings',
        url='https://www.fca.org.uk/news/warnings/rss.xml',
        language='en',
        region='GB',
        kind='enforcement',
        groups=['regulators', 'uk'],
        license='terms',
        max_age_days=2,
        notes='Unauthorised-firm warnings.',
    ),
    FeedSource(
        key='HK_SFC_PRESS_RSS',
        name='HK SFC press releases',
        url='https://www.sfc.hk/en/RSS-Feeds/Press-releases',
        language='en',
        region='HK',
        kind='enforcement',
        groups=['regulators', 'asia'],
        license='terms',
        max_age_days=2,
        notes='',
    ),
    FeedSource(
        key='UK_FCA_NEWS_RSS',
        name='FCA news',
        url='https://www.fca.org.uk/news/rss.xml',
        language='en',
        region='GB',
        kind='enforcement',
        groups=['regulators', 'uk'],
        license='terms',
        max_age_days=2,
        notes='Mixes blogs and press releases.',
    ),
    FeedSource(
        key='UK_NCA_NEWS_RSS',
        name='NCA news',
        url='https://www.nationalcrimeagency.gov.uk/news?format=feed&type=rss',
        language='en',
        region='GB',
        kind='enforcement',
        groups=['regulators', 'uk'],
        license='OGL',
        max_age_days=2,
        notes='',
    ),
    FeedSource(
        key='UK_SFO_NEWS_ATOM',
        name='SFO news (GOV.UK Atom)',
        url='https://www.gov.uk/search/news-and-communications.atom?organisations%5B%5D=serious-fraud-office',
        language='en',
        region='GB',
        kind='enforcement',
        groups=['regulators', 'uk'],
        license='OGL',
        max_age_days=2,
        notes='Atom feed.',
    ),
    FeedSource(
        key='SEC_LITIGATION_RELEASES_RSS',
        name='SEC litigation releases',
        url='https://www.sec.gov/enforcement-litigation/litigation-releases/rss',
        language='en',
        region='US',
        kind='enforcement',
        groups=['regulators', 'us'],
        license='public',
        max_age_days=2,
        notes='',
        needs_contact=True,
    ),
    FeedSource(
        key='US_CFPB_ENFORCEMENT_RSS',
        name='CFPB enforcement actions',
        url='https://www.consumerfinance.gov/enforcement/actions/feed/',
        language='en',
        region='US',
        kind='enforcement',
        groups=['regulators', 'us'],
        license='public',
        max_age_days=2,
        notes='Title is the respondent name.',
    ),
    FeedSource(
        key='US_CFTC_ENFORCEMENT_RSS',
        name='CFTC enforcement',
        url='https://www.cftc.gov/RSS/RSSENF/rssenf.xml',
        language='en',
        region='US',
        kind='enforcement',
        groups=['regulators', 'us'],
        license='public',
        max_age_days=2,
        notes='Empty descriptions.',
    ),
    FeedSource(
        key='US_DOJ_OPA_RSS',
        name='DOJ Office of Public Affairs press releases',
        url='https://www.justice.gov/news/rss?type=press_release&m=1',
        language='en',
        region='US',
        kind='enforcement',
        groups=['regulators', 'us'],
        license='public',
        max_age_days=2,
        notes='',
    ),
    FeedSource(
        key='US_FED_ENFORCEMENT_RSS',
        name='Federal Reserve enforcement actions',
        url='https://www.federalreserve.gov/feeds/press_enforcement.xml',
        language='en',
        region='US',
        kind='enforcement',
        groups=['regulators', 'us'],
        license='public',
        max_age_days=2,
        notes='',
    ),
    FeedSource(
        key='US_SEC_ADMIN_PROCEEDINGS_RSS',
        name='SEC administrative proceedings',
        url='https://www.sec.gov/enforcement-litigation/administrative-proceedings/rss',
        language='en',
        region='US',
        kind='enforcement',
        groups=['regulators', 'us'],
        license='public',
        max_age_days=2,
        notes='',
        needs_contact=True,
    ),
    FeedSource(
        key='US_SEC_PRESS_RSS',
        name='SEC press releases',
        url='https://www.sec.gov/news/pressreleases.rss',
        language='en',
        region='US',
        kind='enforcement',
        groups=['regulators', 'us'],
        license='public',
        max_age_days=2,
        notes='',
        needs_contact=True,
    ),
    FeedSource(
        key='US_SEC_TRADING_SUSPENSIONS_RSS',
        name='SEC trading suspensions',
        url='https://www.sec.gov/enforcement-litigation/trading-suspensions/rss',
        language='en',
        region='US',
        kind='enforcement',
        groups=['regulators', 'us'],
        license='public',
        max_age_days=2,
        notes='Title is the issuer name.',
        needs_contact=True,
    ),
    FeedSource(
        key='AE_DFSA_NEWS_RSS',
        name='DFSA news',
        url='https://www.dfsa.ae/rss',
        language='en',
        region='AE',
        kind='enforcement',
        groups=['regulators', 'gcc', 'mena'],
        license='terms',
        max_age_days=2,
        notes='Mostly general news; low value.',
    ),
    FeedSource(
        key='UK_NCA_MOST_WANTED',
        name='NCA most wanted',
        url='https://www.nationalcrimeagency.gov.uk/most-wanted?format=feed&type=rss',
        language='en',
        region='GB',
        kind='enforcement',
        groups=['regulators', 'uk', 'wanted'],
        license='OGL',
        max_age_days=2,
        notes='Feed of WANTED PERSONS (title = full name); treat as enforcement context, subject to the privacy rules for wanted lists.',
    ),
]
