"""Adverse-media / news feeds (Gulf, pan-Arab and investigative)."""
from __future__ import annotations

from typing import List

from venombot.feeds import FeedSource

FEEDS: List[FeedSource] = [
    FeedSource(
        key='AE_EMARAT_ALYOUM_RSS',
        name='Emarat Al Youm',
        url='https://www.emaratalyoum.com/1.533091?ot=ot.AjaxPageLayout',
        language='ar',
        region='AE',
        kind='adverse_media',
        groups=['media', 'news', 'mena', 'gcc'],
        license='terms',
        max_age_days=2,
        notes='Publisher copyright; headline/snippet monitoring only.',
    ),
    FeedSource(
        key='ICIJ_RSS',
        name='ICIJ',
        url='https://www.icij.org/feed/',
        language='en',
        region='GLOBAL',
        kind='adverse_media',
        groups=['media', 'news', 'investigative'],
        license='terms',
        max_age_days=2,
        notes='Publisher copyright; headline/snippet monitoring only.',
    ),
    FeedSource(
        key='OCCRP_RSS',
        name='OCCRP',
        url='https://www.occrp.org/en/feed',
        language='en',
        region='GLOBAL',
        kind='adverse_media',
        groups=['media', 'news', 'investigative'],
        license='terms',
        max_age_days=2,
        notes='Publisher copyright; headline/snippet monitoring only.',
    ),
    FeedSource(
        key='KW_ALJARIDA_RSS',
        name='Al Jarida (Kuwait)',
        url='https://www.aljarida.com/rssFeed/0',
        language='ar',
        region='KW',
        kind='adverse_media',
        groups=['media', 'news', 'mena', 'gcc'],
        license='terms',
        max_age_days=2,
        notes='Publisher copyright; headline/snippet monitoring only.',
    ),
    FeedSource(
        key='KW_ALRAI_RSS',
        name='Al Rai (Kuwait)',
        url='https://www.alraimedia.com/rssFeed/0',
        language='ar',
        region='KW',
        kind='adverse_media',
        groups=['media', 'news', 'mena', 'gcc'],
        license='terms',
        max_age_days=2,
        notes='Publisher copyright; headline/snippet monitoring only.',
    ),
    FeedSource(
        key='KW_ARAB_TIMES_RSS',
        name='Arab Times (Kuwait)',
        url='https://www.arabtimesonline.com/rssFeed/0/',
        language='en',
        region='KW',
        kind='adverse_media',
        groups=['media', 'news', 'mena', 'gcc'],
        license='terms',
        max_age_days=2,
        notes='Publisher copyright; headline/snippet monitoring only.',
    ),
    FeedSource(
        key='KW_KUWAIT_TIMES_RSS',
        name='Kuwait Times',
        url='https://kuwaittimes.com/rssFeed/0',
        language='en',
        region='KW',
        kind='adverse_media',
        groups=['media', 'news', 'mena', 'gcc'],
        license='terms',
        max_age_days=2,
        notes='Publisher copyright; headline/snippet monitoring only.',
    ),
    FeedSource(
        key='ALJAZEERA_ARABIC_RSS',
        name='Al Jazeera Arabic',
        url='https://www.aljazeera.net/aljazeerarss/a7c186be-1baa-4bd4-9d80-a84db769f779/73d0e1b4-532f-45ef-b135-bfdff8b8cab9',
        language='ar',
        region='QA',
        kind='adverse_media',
        groups=['media', 'news', 'mena', 'gcc'],
        license='terms',
        max_age_days=2,
        notes='Publisher copyright; headline/snippet monitoring only.',
    ),
    FeedSource(
        key='AL_ARABY_RSS',
        name='Al-Araby Al-Jadeed',
        url='https://www.alaraby.co.uk/rss',
        language='ar',
        region='GLOBAL',
        kind='adverse_media',
        groups=['media', 'news', 'mena'],
        license='terms',
        max_age_days=2,
        notes='Publisher copyright; headline/snippet monitoring only.',
    ),
    FeedSource(
        key='AL_QUDS_ALARABI_RSS',
        name='Al-Quds Al-Arabi',
        url='https://www.alquds.co.uk/feed/',
        language='ar',
        region='GLOBAL',
        kind='adverse_media',
        groups=['media', 'news', 'mena'],
        license='terms',
        max_age_days=2,
        notes='Publisher copyright; headline/snippet monitoring only.',
    ),
    FeedSource(
        key='ARAB_NEWS_RSS',
        name='Arab News',
        url='https://www.arabnews.com/rss.xml',
        language='en',
        region='SA',
        kind='adverse_media',
        groups=['media', 'news', 'mena', 'gcc'],
        license='terms',
        max_age_days=2,
        notes='Publisher copyright; headline/snippet monitoring only.',
        headers={'User-Agent': 'Mozilla/5.0'},
    ),
    FeedSource(
        key='ASHARQ_AWSAT_AR_RSS',
        name='Asharq Al-Awsat (Arabic)',
        url='https://aawsat.com/feed',
        language='ar',
        region='SA',
        kind='adverse_media',
        groups=['media', 'news', 'mena', 'gcc'],
        license='terms',
        max_age_days=2,
        notes='Publisher copyright; headline/snippet monitoring only.',
    ),
    FeedSource(
        key='ASHARQ_AWSAT_EN_RSS',
        name='Asharq Al-Awsat (English)',
        url='https://english.aawsat.com/feed',
        language='en',
        region='SA',
        kind='adverse_media',
        groups=['media', 'news', 'mena', 'gcc'],
        license='terms',
        max_age_days=2,
        notes='Publisher copyright; headline/snippet monitoring only.',
    ),
    FeedSource(
        key='CNN_ARABIC_RSS',
        name='CNN Arabic',
        url='https://arabic.cnn.com/api/v1/rss/rss.xml',
        language='ar',
        region='GLOBAL',
        kind='adverse_media',
        groups=['media', 'news', 'mena'],
        license='terms',
        max_age_days=2,
        notes='Publisher copyright; headline/snippet monitoring only.',
    ),
    FeedSource(
        key='DW_ARABIC_RSS',
        name='DW Arabic',
        url='https://rss.dw.com/xml/rss-ar-all',
        language='ar',
        region='GLOBAL',
        kind='adverse_media',
        groups=['media', 'news', 'mena'],
        license='terms',
        max_age_days=2,
        notes='Publisher copyright; headline/snippet monitoring only.',
    ),
    FeedSource(
        key='FRANCE24_ARABIC_RSS',
        name='France 24 Arabic',
        url='https://www.france24.com/ar/rss',
        language='ar',
        region='GLOBAL',
        kind='adverse_media',
        groups=['media', 'news', 'mena'],
        license='terms',
        max_age_days=2,
        notes='Publisher copyright; headline/snippet monitoring only.',
    ),
    FeedSource(
        key='GULF_NEWS_RSS',
        name='Gulf News',
        url='https://gulfnews.com/feed',
        language='en',
        region='AE',
        kind='adverse_media',
        groups=['media', 'news', 'mena', 'gcc'],
        license='terms',
        max_age_days=2,
        notes='Publisher copyright; headline/snippet monitoring only.',
    ),
    FeedSource(
        key='INDEPENDENT_ARABIA_RSS',
        name='Independent Arabia',
        url='https://www.independentarabia.com/rss.xml',
        language='ar',
        region='SA',
        kind='adverse_media',
        groups=['media', 'news', 'mena', 'gcc'],
        license='terms',
        max_age_days=2,
        notes='Publisher copyright; headline/snippet monitoring only.',
    ),
    FeedSource(
        key='NYT_MIDDLEEAST_RSS',
        name='NYT Middle East',
        url='https://rss.nytimes.com/services/xml/rss/nyt/MiddleEast.xml',
        language='en',
        region='GLOBAL',
        kind='adverse_media',
        groups=['media', 'news'],
        license='terms',
        max_age_days=2,
        notes='Publisher copyright; headline/snippet monitoring only.',
    ),
    FeedSource(
        key='SKYNEWS_ARABIA_RSS',
        name='Sky News Arabia',
        url='https://www.skynewsarabia.com/web/rss',
        language='ar',
        region='AE',
        kind='adverse_media',
        groups=['media', 'news', 'mena', 'gcc'],
        license='terms',
        max_age_days=2,
        notes='Publisher copyright; headline/snippet monitoring only.',
    ),
    FeedSource(
        key='THE_NATIONAL_UAE_RSS',
        name='The National (UAE)',
        url='https://www.thenationalnews.com/arc/outboundfeeds/rss/?outputType=xml',
        language='en',
        region='AE',
        kind='adverse_media',
        groups=['media', 'news', 'mena', 'gcc'],
        license='terms',
        max_age_days=2,
        notes='Publisher copyright; headline/snippet monitoring only.',
    ),
    FeedSource(
        key='QA_GULF_TIMES_RSS',
        name='Gulf Times (Qatar)',
        url='https://www.gulf-times.com/rssFeed/0',
        language='en',
        region='QA',
        kind='adverse_media',
        groups=['media', 'news', 'mena', 'gcc'],
        license='terms',
        max_age_days=2,
        notes='Publisher copyright; headline/snippet monitoring only.',
    ),
    FeedSource(
        key='SA_SAUDI_GAZETTE_RSS',
        name='Saudi Gazette',
        url='https://saudigazette.com.sa/rssFeed/0',
        language='en',
        region='SA',
        kind='adverse_media',
        groups=['media', 'news', 'mena', 'gcc'],
        license='terms',
        max_age_days=2,
        notes='Publisher copyright; headline/snippet monitoring only.',
    ),
]
