"""Generate docs/SOURCES.md from the three registries (lists, live providers, feeds).

Run: python3 scripts/gen_sources_doc.py
The doc is generated, never hand-edited, so it cannot drift from the code.
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from venombot.feeds import all_feeds  # noqa: E402
from venombot.live import all_providers  # noqa: E402
from venombot.lists import all_list_sources  # noqa: E402

OUT = Path(__file__).resolve().parent.parent / "docs" / "SOURCES.md"


def _cell(text: str, n: int = 90) -> str:
    return " ".join(str(text).split()).replace("|", "\\|")[:n]


def main() -> int:
    lists = all_list_sources()
    live = all_providers()
    feeds = all_feeds()
    own = {k: s for k, s in lists.items() if not k.startswith(("OS_", "OSC_"))}
    os_ = {k: s for k, s in lists.items() if k.startswith(("OS_", "OSC_"))}

    lines = [
        "# Sources",
        "",
        "Generated by `scripts/gen_sources_doc.py` from the code registries; do not edit by hand.",
        "",
        f"- **{len(own)} direct list sources** (parsed from the publisher's own file)",
        f"- **{len(os_)} OpenSanctions datasets** registered (the built-in seed; run "
        "`venombot lists --refresh-opensanctions` for the full ~440; CC BY-NC, non-commercial)",
        f"- **{len(live)} live providers** (per-subject search APIs; opt-in, send the name to a third party)",
        f"- **{len(feeds)} feeds** (RSS/Atom news and regulator press, searched locally)",
        "",
        "Load lists with `venombot update --group <group>`; query live providers with "
        "`screen --live`; refresh feeds with `venombot media update`.",
        "",
        "## Direct list sources",
        "",
    ]
    by_type = defaultdict(list)
    for s in own.values():
        by_type[s.list_type].append(s)
    for lt in sorted(by_type):
        lines += [f"### {lt} ({len(by_type[lt])})", "",
                  "| Key | Jur. | Licence | Key needed | Groups | Notes |", "|---|---|---|---|---|---|"]
        for s in sorted(by_type[lt], key=lambda s: s.key):
            lines.append(f"| `{s.key}` | {s.jurisdiction} | {s.license} | {s.api_key_env or '—'} | "
                         f"{', '.join(s.groups)} | {_cell(s.notes)} |")
        lines.append("")

    lines += ["## OpenSanctions datasets (seed)", "",
              "| Key | Jur. | Type | Notes |", "|---|---|---|---|"]
    for s in sorted(os_.values(), key=lambda s: s.key):
        lines.append(f"| `{s.key}` | {s.jurisdiction} | {s.list_type} | {_cell(s.notes)} |")

    lines += ["", "## Live providers", "",
              "| Key | Kind | Jur. | Key needed | Groups | Notes |", "|---|---|---|---|---|---|"]
    for p in sorted(live.values(), key=lambda p: p.key):
        lines.append(f"| `{p.key}` | {p.kind} | {p.jurisdiction} | {p.api_key_env or '—'} | "
                     f"{', '.join(p.groups)} | {_cell(p.notes)} |")

    lines += ["", "## Feeds", "",
              "| Key | Kind | Lang | Region | Notes |", "|---|---|---|---|---|"]
    for f in sorted(feeds.values(), key=lambda f: f.key):
        lines.append(f"| `{f.key}` | {f.kind} | {f.language} | {f.region} | {_cell(f.notes)} |")

    lines += ["", "## Known gaps", "",
              "- Legacy binary `.xls` and PDF-only lists are not parsed (UAE UAEIEC `.xls`, Bahrain gazette PDF, "
              "Oman PDFs, India NSE `.xls`); the OpenSanctions mirrors cover the UAE and others.",
              "- Several publishers block non-browser User-Agents; those sources set an explicit `headers` "
              "override (see each source's `headers`).",
              "- Some publishers rotate hashed file names per update (Turkey MASAK, Tunisia, Kenya, Indonesia, "
              "Malaysia, Azerbaijan); the `notes` explain how to rediscover the current URL.",
              "- Wanted-person, ICIJ and several registry parsers were written from format notes and synthetic "
              "fixtures without a verified full parse of the real file.",
              "- Country-risk data (FATF, Basel, CPI) is not yet ingested.", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}: {len(own)} lists, {len(os_)} OS datasets, {len(live)} live, {len(feeds)} feeds")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
